<?php

return [
    'accessibility', 'activity', 'air-vent', 'alarm-clock', 'album', 'align-center', 'align-justify', 'align-left', 'align-right',
    'anchor', 'aperture', 'apple', 'archive', 'arrow-big-down', 'arrow-big-left', 'arrow-big-right', 'arrow-big-up', 'arrow-down',
    'arrow-down-left', 'arrow-down-right', 'arrow-left', 'arrow-right', 'arrow-up', 'arrow-up-left', 'arrow-up-right',
    'asterisk', 'at-sign', 'award', 'baby', 'backpack', 'badge', 'badge-check', 'ban', 'banana', 'bar-chart', 'bar-chart-2',
    'baseline', 'battery', 'battery-charging', 'battery-low', 'beaker', 'bed', 'bed-double', 'beer', 'bell', 'bell-off',
    'bike', 'binary', 'bluetooth', 'bold', 'book', 'book-open', 'bookmark', 'bot', 'box', 'box-select', 'boxes',
    'briefcase', 'brush', 'bug', 'building', 'building-2', 'bus', 'cake', 'calculator', 'calendar', 'calendar-check',
    'calendar-clock', 'calendar-days', 'camera', 'camera-off', 'car', 'carrot', 'cast', 'check', 'check-circle',
    'check-square', 'chef-hat', 'chevron-down', 'chevron-left', 'chevron-right', 'chevron-up', 'chrome',
    'circle', 'circle-dot', 'circle-off', 'circuit-board', 'clapperboard', 'clipboard', 'clock', 'cloud',
    'cloud-download', 'cloud-rain', 'cloud-snow', 'cloud-sun', 'cloud-upload', 'code', 'code-2', 'coffee',
    'cog', 'coins', 'columns', 'command', 'compass', 'computer', 'concierge-bell', 'contact', 'copy', 'copyright',
    'credit-card', 'crop', 'crosshair', 'crown', 'cup-soda', 'curly-braces', 'database', 'delete', 'diamond',
    'dice-1', 'dice-2', 'dice-3', 'dice-4', 'dice-5', 'dice-6', 'disc', 'divide', 'dna', 'dog', 'dollar-sign',
    'download', 'dribbble', 'droplet', 'droplets', 'drumstick', 'dumbbell', 'ear', 'edit', 'edit-2', 'edit-3',
    'egg', 'equal', 'eraser', 'euro', 'expand', 'external-link', 'eye', 'eye-off', 'facebook', 'factory',
    'fan', 'fast-forward', 'feather', 'file', 'file-check', 'file-edit', 'file-minus', 'file-plus', 'file-text',
    'film', 'filter', 'fingerprint', 'flag', 'flame', 'flashlight', 'flask-conical', 'flip-horizontal', 'flip-vertical',
    'flower', 'flower-2', 'focus', 'folder', 'folder-open', 'footprints', 'fork-knife', 'form-input', 'frame',
    'frown', 'fuel', 'gamepad', 'gauge', 'gem', 'ghost', 'gift', 'git-branch', 'git-commit', 'git-merge',
    'github', 'globe', 'grape', 'grid', 'grip', 'grip-horizontal', 'grip-vertical', 'hammer', 'hand', 'hard-drive',
    'hash', 'haze', 'headphones', 'heart', 'help-circle', 'hexagon', 'highlighter', 'history', 'home', 'ice-cream',
    'image', 'import', 'inbox', 'indent', 'infinity', 'info', 'instagram', 'italic', 'key', 'keyboard',
    'lamp', 'laptop', 'lasso', 'laugh', 'layers', 'layout', 'layout-dashboard', 'layout-grid', 'layout-list',
    'leaf', 'library', 'life-buoy', 'lightbulb', 'line-chart', 'link', 'link-2', 'linkedin', 'list', 'list-checks',
    'list-order', 'list-plus', 'loader', 'lock', 'log-in', 'log-out', 'luggage', 'mail', 'map', 'map-pin',
    'maximize', 'medal', 'megaphone', 'menu', 'message-circle', 'message-square', 'mic', 'mic-off', 'microscope',
    'microwave', 'minimize', 'minus', 'minus-circle', 'monitor', 'moon', 'more-horizontal', 'more-vertical',
    'mountain', 'mouse-pointer', 'move', 'music', 'navigation', 'network', 'newspaper', 'package', 'paint-bucket',
    'palette', 'panel-left', 'panel-top', 'paperclip', 'pause', 'pause-circle', 'pen-tool', 'pencil', 'percent',
    'phone', 'phone-call', 'phone-off', 'pie-chart', 'piggy-bank', 'pin', 'pin-off', 'pizza', 'plane',
    'play', 'play-circle', 'plug', 'plus', 'plus-circle', 'plus-square', 'pocket', 'podcast', 'power',
    'printer', 'puzzle', 'qr-code', 'quote', 'radio', 'receipt', 'refresh-ccw', 'repeat', 'rewind', 'rocket',
    'rss', 'ruler', 'save', 'scale', 'scissors', 'search', 'send', 'server', 'settings', 'share', 'share-2',
    'shield', 'shield-check', 'shirt', 'shopping-bag', 'shopping-cart', 'shovel', 'shower-head', 'shrink',
    'sidebar', 'skull', 'smartphone', 'smile', 'snowflake', 'sort-asc', 'sort-desc', 'speaker', 'sprout',
    'square', 'star', 'sticky-note', 'store', 'strikethrough', 'sun', 'sunrise', 'sunset', 'table', 'tablet',
    'tag', 'target', 'tent', 'terminal', 'thermometer', 'thumbs-down', 'thumbs-up', 'ticket', 'timer',
    'toggle-left', 'toggle-right', 'trash', 'trash-2', 'trending-down', 'trending-up', 'triangle', 'trophy',
    'truck', 'tv', 'twitter', 'type', 'umbrella', 'underline', 'undo', 'unlock', 'upload', 'user', 'user-check',
    'user-minus', 'user-plus', 'user-x', 'users', 'utensils', 'video', 'video-off', 'voicemail', 'volume',
    'volume-1', 'volume-2', 'volume-x', 'wallet', 'watch', 'waves', 'wifi', 'wifi-off', 'wind', 'wine',
    'wrap-text', 'wrench', 'x', 'x-circle', 'youtube', 'zap', 'zoom-in', 'zoom-out',
];
